pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    dotnet build -c $(buildConfiguration)
    dotnet test ./src/VSTS.Net.Tests -c $(buildConfiguration) -l:trx /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[NUnit3.TestAdapter]*" /p:ExcludeByFile="../Vsts.Net/Models/*.cs"
    dotnet publish -c $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultFilters: '**/*.trx'
    
- task: PublishBuildArtifacts@1